import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image';
import styles from '../styles/index.module.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Navbar, Container, Nav, NavDropdown, Col, Row } from 'react-bootstrap';
import SideNav from '../components/SideNav';
import list from "../source/bcdice.json"
import { useAtomValue } from 'jotai';
import { selectAtom } from '../components/jotai';

const D66SortTypeMap  : {[key:string]:string} = {
  "no_sort" : "ソート：なし",
  "asc" : "昇順",
  "dsc" : "降順"
}

const RoundTypeMap: {[key:string]:string} = {
  "ceil" : "切り上げ",
  "floor" : "切り捨て",
  "round" : "四捨五入"
} 

function NavBar() {
  return (
    <Navbar bg="light" expand="lg">
      <Container>
        <Navbar.Brand href="#home">DiceBook</Navbar.Brand>
        <Navbar.Toggle aria-controls="basic-navbar-nav" />
        <Navbar.Collapse id="basic-navbar-nav">
          <Nav className="me-auto">
            <Nav.Link href="#home">Home</Nav.Link>
            <Nav.Link href="#link">Link</Nav.Link>
            <NavDropdown title="Dropdown" id="basic-nav-dropdown">
              <NavDropdown.Item href="#action/3.1">Action</NavDropdown.Item>
              <NavDropdown.Item href="#action/3.2">
                Another action
              </NavDropdown.Item>
              <NavDropdown.Item href="#action/3.3">Something</NavDropdown.Item>
              <NavDropdown.Divider />
              <NavDropdown.Item href="#action/3.4">
                Separated link
              </NavDropdown.Item>
            </NavDropdown>
          </Nav>
        </Navbar.Collapse>
      </Container>
    </Navbar>
  );
}




const Home: NextPage = () => {
  const selected = useAtomValue(selectAtom)
  return (
    <div className={styles.container}>
      <Head>
        <title>DiceBook ⚀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />


      <Container fluid>
        <Row>
          <Col xs={6} md={3}><SideNav list={list.list} /></Col>
          <Col xs={12} md={9} as="main">
            <h2>{selected?.name}</h2>
            <div className="p-2 rounded border bg-light">
              {/* { selected?.prefixes } */}
              {selected?.sort_add_dice}
              {selected?.sort_barabara_dice}
              { D66SortTypeMap[selected?.d66_sort_type] }
              { selected?.sides_implicit_d}面
              { RoundTypeMap[selected?.round_type]}
            </div>
            <div style={{whiteSpace: "pre"}}>{selected?.help}</div>
          </Col>
        </Row>
      </Container>

      <footer>
        DiceBook
      </footer>
    </div>
  )
}

export default Home
